[USER_DB]
host = "postgres"
port = "5432"
user = "postgres"
passw = "control098"
dbname = "users"

[AUTORIZATION]
register_codes = ["askjas1872", "hei22012025","dba22012025"]

[MISCELLANEOUS]
logo = "static/new-linkedby.png"
subject = "LinkedBy_monitor_kafka"
title = "Monitoramento Conectores Kafka"
autorefresh = 600000
